# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IXLzXYbVd2vuhRkZljaQ1AD7Vz9ylVps
"""

pip install flask

from flask import Flask, request, jsonify
import joblib

app = Flask(__name__)

# Load the trained ML model
model = joblib.load('model.pkl')

@app.route('/predict', methods=['POST'])
def predict_click():
    try:
        # Get user input from the request
        data = request.get_json()
        Age = data['Age']
        Gender = data['Gender']
        Time_spent = data['Time_spent']

        # Perform prediction using the ML model
        prediction = log_reg_model.predict([[Age, Gender, Time_spent]])

        # Return the prediction result
        return jsonify({'prediction': bool(prediction[0])})

    except Exception as e:
        return jsonify({'error': str(e)}), 400

if __name__ == '__main__':
    app.run(debug=True)
